name: PocketJobs
main: MinecrafterJPN\PocketJobs
author: MinecrafterJPN
version: 2.2dev
api: [4.0.0]
load: POSTWORLD
description: Introduces job into your world
website: https://github.com/MinecrafterJPN/PocketJobs
depend: [PocketMoney]
commands:
 jobs:
  desciption: PocketJobs main command
  usage: /jobs [subcommand]
  permission: pocketjobs.command
permissions:
  pocketjobs.command:
    default: true
    description: Allows using all the PocketJobs commands
